name: Test CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: update
        run: npm update

      - name: test
        run: npm run test

      - name: build
        run: npm run build
